#include "AnimUpdate_Common.ush"

//=============================================================
// バインディング
// AnimStateTextureのレイアウト:
//   Width  = MaxInstances
//   Height = 2行
//   Row 0  : float4(AnimTime, PrevAnimTime, NextAnimTime, BlendWeight)
//   Row 1  : float4(AnimIndex, NextAnimIndex, Flags, BlendSpeed)
//
// AnimInfoTextureのレイアウト:
//   Width  = アニメーション数
//   Height = 1行
//   各テクセル : float4(StartFrame, NumFrames, AnimNum, 0)
//=============================================================

RWTexture2D<float4>                 AnimStateTextureReadWrite;
Texture2D<float4>                   AnimInfoTexture;
RWStructuredBuffer<FGPUAnimState>   GPUAnimStateBuffer;
StructuredBuffer<uint>              ActiveInstanceIndexBuffer;

float   DeltaTime;
float   SampleRate;
uint    ActiveInstanceCount;
uint    MaxInstances;

//=============================================================
// ヘルパー関数
//=============================================================

/** アニメのフレーム総数を取得 */
float GetNumFrames(int AnimIndex)
{
    return AnimInfoTexture[uint2(AnimIndex, 0)].y;
}

float GetStartFrames(int AnimIndex)
{
    return AnimInfoTexture[uint2(AnimIndex, 0)].x;
}

//=============================================================
// Pass 2: アニメ状態の更新（毎フレーム）
//=============================================================

[numthreads(64, 1, 1)]
void MainCS(uint3 id : SV_DispatchThreadID)
{
    // アクティブなインスタンスIDを取得
    uint activeSlot = id.x;
    
    // 実際に更新するインスタンスのIDをActiveInstanceIndexBufferから取得
    //uint idx = ActiveInstanceIndexBuffer[id.x];
    uint idx = id.x;
    if (idx >= MaxInstances)
    {
        return;
    }

    //----------------------------------------------------------
    // テクスチャから現在の状態を読む
    //----------------------------------------------------------
    FGPUAnimState AnimState = GPUAnimStateBuffer[idx];
    //float AnimTime = row0.x;
    //float PrevAnimTime = row0.y;
    //float NextAnimTime = row0.z;
    //float BlendWeight = row0.w;

    //float4 row1 = MidTextureRead[uint2(idx, 1)];
    //int AnimIndex = (int) row1.x;
    //int NextAnimIndex = (int) row1.y;
    //uint Flags = (uint) row1.z;
    //float BlendSpeed = row1.w;

    bool    bLooping      = (AnimState.Flags & FLAG_LOOPING) != 0;
    float   bBlending     = (AnimState.Flags & FLAG_BLENDING) != 0 ? 1.0f : 0.0f;
    float   CurrentFrame  = 0.0;
    float   PrevFrame     = 0.0;
    float   NextFrame     = 0.0f;
    
    float   StartFrame      = GetStartFrames(AnimState.AnimIndex);
    float   EndFrames       = GetNumFrames(AnimState.AnimIndex);
    float   ActualNumFrames = EndFrames - StartFrame;               // 実際のフレーム数

    //----------------------------------------------------------
    // アニメ時間の更新
    //----------------------------------------------------------
    AnimState.PrevAnimTime = AnimState.AnimTime;

    if (!bBlending)
    {
        AnimState.AnimTime += DeltaTime;

        // ループ終了検知
        float CurrRaw   = AnimState.AnimTime * SampleRate;      // DeltaTimeをフレームに変換
        float PrevRaw   = AnimState.PrevAnimTime * SampleRate;
        // 現在のフレーム数に、アニメの開始フレーム数を加算してテクスチャに書き込む
        // これにより、アニメの開始フレームが０以外の場合でも正しいテクスチャのUV座標を参照できる
        CurrentFrame    = StartFrame + fmod(CurrRaw, ActualNumFrames);
        PrevFrame       = StartFrame + fmod(PrevRaw, ActualNumFrames);

        // 実際のフレーム数でループ検出
        bool bLoopedOver = (int) (PrevRaw / ActualNumFrames) < (int) (CurrRaw / ActualNumFrames);
        

        if (bLoopedOver && !bLooping)
        {
        // 非ループアニメが1周した → 終了フラグを立ててブレンド待機
        //Flags |= FLAG_FINISHED;
            AnimState.Flags |= FLAG_BLENDING;
            bBlending       = true;
        }
    }
    else
    {
        // ブレンド中
        AnimState.NextAnimTime  += DeltaTime;
        AnimState.BlendWeight   += DeltaTime / AnimState.BlendSpeed;
        
        float PrevRaw   = AnimState.PrevAnimTime * SampleRate;
        float CurrRaw   = AnimState.AnimTime * SampleRate;
        float NextRaw   = AnimState.NextAnimTime * SampleRate;
        
        // 現在アニメーションは止めているが、使うのでフレーム数を計算しておく
        CurrentFrame    = fmod(CurrRaw, ActualNumFrames);
        PrevFrame       = fmod(PrevRaw, ActualNumFrames);
        
        // 次アニメ側
        float NextStartFrame        = GetStartFrames(AnimState.NextAnimIndex);
        float NextEndFrame          = GetNumFrames(AnimState.NextAnimIndex);
        float NextActualNumFrames   = NextEndFrame - NextStartFrame;
        
        NextFrame = NextStartFrame + fmod(NextRaw, NextActualNumFrames);
        
        if (AnimState.BlendWeight >= 1.0f)
        {
            // ブレンド完了・アニメ切り替え
            CurrentFrame                = NextFrame;
            PrevFrame                   = NextFrame;
            EndFrames                   = GetNumFrames(AnimState.NextAnimIndex);
            float NextLoopDuration      = NextActualNumFrames / SampleRate;
            AnimState.BlendWeight       = 0.0f;
            AnimState.AnimIndex         = AnimState.NextAnimIndex;
            AnimState.AnimTime          = fmod(AnimState.NextAnimTime, NextLoopDuration);
            AnimState.NextAnimTime      = 0.0f;
            AnimState.Flags &= ~FLAG_BLENDING;
            //Flags &= ~FLAG_FINISHED;
            
            bBlending = 0.0f;
        }
    }

    GPUAnimStateBuffer[idx] = AnimState;
    
    //----------------------------------------------------------
    // テクスチャに書き戻す
    //----------------------------------------------------------
    float NextStartFrame    = GetStartFrames(AnimState.NextAnimIndex);
    float NextNumFrames     = GetNumFrames(AnimState.NextAnimIndex);
    
    AnimStateTextureReadWrite[uint2(idx, 0)] = float4(CurrentFrame, PrevFrame, NextFrame, GetStartFrames(AnimState.AnimIndex));
    AnimStateTextureReadWrite[uint2(idx, 1)] = float4(EndFrames, bBlending, NextStartFrame, AnimState.BlendWeight);
}
